In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=['the glass of milk',

    'the glass of juice',

    'the cup of tea',

    'I am a good boy',

    'I am a good developer',

    'understand the meaning of words',

    'your videos are good',]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [11]:
voc_size=10000

In [12]:
one_hot_repn=[one_hot(words,voc_size) for words in sent]
one_hot_repn

[[7948, 3503, 5329, 2450],
 [7948, 3503, 5329, 3776],
 [7948, 416, 5329, 105],
 [687, 5356, 2603, 1327, 9867],
 [687, 5356, 2603, 1327, 7918],
 [6180, 7948, 6829, 5329, 998],
 [4581, 2642, 448, 1327]]

In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
import numpy as np

In [17]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repn,padding='pre',maxlen=sent_length)

In [18]:
embedded_docs

array([[   0,    0,    0,    0, 7948, 3503, 5329, 2450],
       [   0,    0,    0,    0, 7948, 3503, 5329, 3776],
       [   0,    0,    0,    0, 7948,  416, 5329,  105],
       [   0,    0,    0,  687, 5356, 2603, 1327, 9867],
       [   0,    0,    0,  687, 5356, 2603, 1327, 7918],
       [   0,    0,    0, 6180, 7948, 6829, 5329,  998],
       [   0,    0,    0,    0, 4581, 2642,  448, 1327]])

In [19]:
dim=10

In [29]:
model=Sequential()
model.add(Embedding(voc_size,dim))
model.build(input_shape=(None,sent_length))
model.compile('adam','mse')

In [30]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 495ms/step


array([[[-0.01321229, -0.04183833,  0.01761765, -0.01427146,
          0.0041144 ,  0.01095786, -0.0296229 , -0.04536172,
          0.00761743, -0.04087857],
        [-0.01321229, -0.04183833,  0.01761765, -0.01427146,
          0.0041144 ,  0.01095786, -0.0296229 , -0.04536172,
          0.00761743, -0.04087857],
        [-0.01321229, -0.04183833,  0.01761765, -0.01427146,
          0.0041144 ,  0.01095786, -0.0296229 , -0.04536172,
          0.00761743, -0.04087857],
        [-0.01321229, -0.04183833,  0.01761765, -0.01427146,
          0.0041144 ,  0.01095786, -0.0296229 , -0.04536172,
          0.00761743, -0.04087857],
        [ 0.03980568, -0.01935828, -0.00549768,  0.0490925 ,
         -0.04319746,  0.02215791, -0.01178871,  0.00862728,
         -0.04954479,  0.00390106],
        [ 0.00956007, -0.03790589,  0.02495353, -0.04158161,
         -0.00502653,  0.02300285,  0.01501239,  0.04213853,
          0.00845625,  0.01509768],
        [ 0.02319899, -0.04917042,  0.0107122 ,  0.0

In [33]:
model.predict(embedded_docs[0].reshape(1,sent_length))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step


array([[[-0.01321229, -0.04183833,  0.01761765, -0.01427146,
          0.0041144 ,  0.01095786, -0.0296229 , -0.04536172,
          0.00761743, -0.04087857],
        [-0.01321229, -0.04183833,  0.01761765, -0.01427146,
          0.0041144 ,  0.01095786, -0.0296229 , -0.04536172,
          0.00761743, -0.04087857],
        [-0.01321229, -0.04183833,  0.01761765, -0.01427146,
          0.0041144 ,  0.01095786, -0.0296229 , -0.04536172,
          0.00761743, -0.04087857],
        [-0.01321229, -0.04183833,  0.01761765, -0.01427146,
          0.0041144 ,  0.01095786, -0.0296229 , -0.04536172,
          0.00761743, -0.04087857],
        [ 0.03980568, -0.01935828, -0.00549768,  0.0490925 ,
         -0.04319746,  0.02215791, -0.01178871,  0.00862728,
         -0.04954479,  0.00390106],
        [ 0.00956007, -0.03790589,  0.02495353, -0.04158161,
         -0.00502653,  0.02300285,  0.01501239,  0.04213853,
          0.00845625,  0.01509768],
        [ 0.02319899, -0.04917042,  0.0107122 ,  0.0